### PR TITLE
`--functional`: wait for wrapper to end its operations before destroing the child process

### LINKED ISSUE #786: Unable to merge junit logs (first worker output empty file)
| Q | A
| --- | ---
| ParaTest version | 7.2.5
| PHPUnit version | 10.3.2
| PHP version | 8.1.22

#### Summary

Same error as was discussed here https://github.com/paratestphp/paratest/issues/745 but with small example.

#### Current behavior

It crashed with exception on joining junit logs files in the end of running tests.

If assert is enabled:
`PHP Fatal error:  Uncaught AssertionError: assert($logFile->isFile() && 0 < (int)$logFile->getSize()) in /var/www/vendor/brianium/paratest/src/JUnit/TestSuite.php:41
Stack trace:
#0 /var/www/vendor/brianium/paratest/src/JUnit/TestSuite.php(41): assert()
#1 /var/www/vendor/brianium/paratest/src/JUnit/LogMerger.php(29): ParaTest\JUnit\TestSuite::fromFile()
#2 /var/www/vendor/brianium/paratest/src/WrapperRunner/WrapperRunner.php(346): ParaTest\JUnit\LogMerger->merge()`

if not ex. occurs later:

`String could not be parsed as XML
...vendor/brianium/paratest/src/JUnit/TestSuite.php:51`

#### How to reproduce: command, code and error stack trace

Reproducible env/error: https://github.com/pistej/parates-bug

#### Expected behavior

I expect junit logs to be merged and report.xml created.

### PR DESCRIPTION
**Pull request by Slamdunk**
Fix https://github.com/paratestphp/paratest/issues/786

### CODE REVIEW

File: src/WrapperRunner/WrapperRunner.php [hunk 1]
```diff
@@ -237,11 +237,11 @@ private function startWorker(int $token): WrapperWorker
...
     {
-        // Mutation Testing tells us that the following `unset()` already destroys
-        // the `WrapperWorker`, which destroys the Symfony's `Process`, which
-        // automatically calls `Process::stop` within `Process::__destruct()`.
-        // But we prefer to have an explicit stops.
         $this->workers[$token]->stop();
+        // We need to wait for ApplicationForWrapperWorker::end to end
+        while ($this->workers[$token]->isRunning()) {
+            usleep(self::CYCLE_SLEEP);
+        }
```
Comment (Slamdunk) [inline src/WrapperRunner/WrapperRunner.php:244]: @nunomaduro can you apply this fix to Pest too please?
