### PR TITLE
BaseRunner -> Writer $name

### LINKED ISSUE #520: PHPUnit 9 BaseRunner -> Writer error
```
PHP Warning:  assert(): assert($path !== null) failed in /var/www/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php on line 139

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ParaTest\Logging\JUnit\Writer::__construct() must be of the type string, null given, called in /var/www/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php on line 141 and defined in /var/www/vendor/brianium/paratest/src/Logging/JUnit/Writer.php:55
```

When called with
```
vendor/bin/paratest \
  --colors \
  --log-junit=".artifacts/junit/parallel.xml" \
  --testsuite "parallel" \
  --processes "8"
```

### PR DESCRIPTION
**Pull request by matthewnessworthy**
Fixes #520

### CODE REVIEW

**Comment by matthewnessworthy** [comment]
@Slamdunk would you mind reviewing and potentially merging/tagging if you are happy with it?

File: src/Runners/PHPUnit/BaseRunner.php [hunk 1]
```diff
@@ -135,10 +135,9 @@ private function complete(): void
             return;
         }
 
-        $path = $this->options->path();
-        assert($path !== null);
+        $name = $this->options->path() ?? '';
```
Comment (Slamdunk) [inline src/Runners/PHPUnit/BaseRunner.php:138]: The default PHPUnit behavior is to put an empty string

**Comment by Slamdunk** [comment]
Thank you
