### PR TITLE
Respect configuration options of text coverage

### LINKED ISSUE #385: coverage-text in file ?
Hi!

It's not possible to put the coverage in text format inside a file?  
  
Currently, i have the following error:  
`The "--coverage-text" option does not accept a value.`  
  
Thx.

### PR DESCRIPTION
**Pull request by LeoVie**
This resolves #385

`showOnlySummary` was changed to `false` in `test/fixtures/phpunit-fully-configured.xml`, as the other tests rely on the whole text coverage report being created.

I created `test/fixtures/phpunit-coverage-text-show-only-summary.xml`, which only differs from `test/fixtures/phpunit-fully-configured.xml` in part of the option `showOnlySummary` being set to `true`.

For being able to use the dataProvider `generateTextProvider` it was neccessary to overwrite the default configuration in `test/Unit/Coverage/CoverageReporterTest.php`. Therefore I extracted a method `createCoverageReporter` which takes a fixture path as an argument (to reduce code redundancy). This function is called in `setup`, as well as in the test method `testGenerateText`.

With `showOnlySummary` set to false, the text coverage report looks like this:
```
Code Coverage Report:   
  2021-08-17 07:45:37   
                        
 Summary:               
  Classes: 100.00% (1/1)
  Methods: 100.00% (1/1)
  Lines:   100.00% (1/1)

ParaTest\Tests\Unit\Coverage\CoverageReporterTest
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% (  1/  1)
```

With `showOnlySummary` set to true, the text coverage report looks like this:
```
Code Coverage Report Summary:
  Classes: 100.00% (1/1)     
  Methods: 100.00% (1/1)     
  Lines:   100.00% (1/1)
```
So the test checks, if the report contains `Code Coverage Report:`, when `showOnlySummary` is false and `Code Coverage Report Summary:`, when `showOnlySummary` is true.

In lines 103 and 104, the parameters `lowUpperBound` and `highLowerBound` are hard coded to the default parameter values. PHPUnit does not seem to make these parameters configurable for text coverage.

### CODE REVIEW

**Comment by LeoVie** [comment]
May I ping on this, @Slamdunk @andreasschroth? :) I'm open to improvement suggestions.

File: src/Coverage/CoverageReporter.php [hunk 1]
```diff
@@ -98,6 +98,14 @@ public function php(string $target): void
     public function text(): string
     {
         $text = new Text();
+        if ($this->codeCoverageConfiguration !== null && $this->codeCoverageConfiguration->hasText()) {
+            $text = new Text(
+                50,
+                90,
```
Comment (Slamdunk) [inline src/Coverage/CoverageReporter.php:104]: PHPUnit gets this values from `coverageReportHtmlType`, can we do the same here and default to 50/90 when those are not set?

Comment (LeoVie) [reply src/Coverage/CoverageReporter.php]: If I got you right, it's implemented like this, now.

**Review by Slamdunk — APPROVED** [review]

**Comment by Slamdunk** [comment]
Thank you @LeoVie
