### PR TITLE
Fix `--functional` progress output

### LINKED ISSUE #826: Bad progress output with option --functional
| Q | A
| --- | ---
| ParaTest version | 7.3.1
| PHPUnit version | 10.5.3
| PHP version | 8.3.0

#### Summary

I've just updated the versions of Paratest and Phpunit. When I use the "-functional" option, I get a problem in the output. The progress exceeds the actual number of tests.

This is my phpunit.xml :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.5/phpunit.xsd" colors="true" bootstrap="tests/bootstrap.php" backupGlobals="false">
  <php>
    <ini name="error_reporting" value="-1"/>
    <server name="APP_ENV" value="test" force="true"/>
    <env name="APP_ENV" value="test" force="true"/>
    <server name="SHELL_VERBOSITY" value="-1"/>
    <server name="SYMFONY_PHPUNIT_REMOVE" value=""/>
    <server name="SYMFONY_PHPUNIT_VERSION" value="10.5"/>
    <server name="KERNEL_CLASS" value="App\Kernel"/>
  </php>
  <testsuites>
    <testsuite name="Core">
      <directory>tests/Controller</directory>
    </testsuite>
  </testsuites>
  <extensions>
    <bootstrap class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension"/>
  </extensions>
  <source>
    <include>
      <directory>src</directory>
      <directory>modules/*/src</directory>
    </include>
    <exclude>
      <directory>src/Contract</directory>
      <directory>src/DataFixtures</directory>
      <directory>src/DataFixtures</directory>
      <directory>src/DeliveryServiceTemplates</directory>
      <directory>src/DependencyInjection</directory>
      <directory>src/Deploy</directory>
      <directory>src/Doctrine</directory>
      <directory>src/Entity</directory>
      <directory>src/Enum</directory>
      <directory>src/Event</directory>
      <directory>src/Factory</directory>
      <directory>src/MailEvent</directory>
      <directory>src/Model</directory>
      <directory>src/Page</directory>
      <directory>src/Routing</directory>
      <directory>src/Translation</directory>
      <file>src/CoreBundle.php</file>
      <file>src/Kernel.php</file>
      <directory>modules/*/src/Contract</directory>
      <directory>modules/*/src/DataFixtures</directory>
      <directory>modules/*/src/DeliveryServiceTemplates</directory>
      <directory>modules/*/src/DependencyInjection</directory>
      <directory>modules/*/src/Deploy</directory>
      <directory>modules/*/src/Doctrine</directory>
      <directory>modules/*/src/Entity</directory>
      <directory>modules/*/src/Enum</directory>
      <directory>modules/*/src/Event</directory>
      <directory>modules/*/src/Factory</directory>
      <directory>modules/*/src/MailEvent</directory>
      <directory>modules/*/src/Model</directory>
      <directory>modules/*/src/Page</directory>
      <directory>modules/*/src/Routing</directory>
      <directory>modules/*/src/Translation</directory>
    </exclude>
  </source>
</phpunit>
```

#### Current behavior

Result without "--functional" :

paratest_without_functional

Result with "--functional" :

paratest_with_functional

#### How to reproduce: command, code and error stack trace

Without bug :

`php ./vendor/bin/paratest --configuration=phpunit.xml.dist --no-coverage -p8`

With bug :

`php ./vendor/bin/paratest --configuration=phpunit.xml.dist --no-coverage -p8 --functional`

You need to have methods with the same beginning of names in the same class.

#### Expected behavior

Obtain the same output with and without the option "--functional"

### PR DESCRIPTION
**Pull request by ax-ml**
Fix #826

### CODE REVIEW

**Review by deluxetom — APPROVED** [review]

File: test/Unit/WrapperRunner/WrapperRunnerTest.php [hunk 1]
```diff
@@ -607,7 +607,7 @@ public function testFunctionalParallelization(): void
         $this->bareOptions['--functional'] = true;
 
         $runnerResult = $this->runRunner();
-        self::assertStringContainsString('.......', $runnerResult->output);
+        self::assertStringContainsString('.', $runnerResult->output);
```
Comment (Slamdunk) [inline test/Unit/WrapperRunner/WrapperRunnerTest.php]: All the mutants failed in https://github.com/paratestphp/paratest/actions/runs/7444310647/job/20256902107?pr=828 scare me: can we make this assertion a bit more exact?

**Review by Slamdunk — CHANGES_REQUESTED** [review]

**Review by deluxetom — APPROVED** [review]

File: test/Unit/WrapperRunner/WrapperRunnerTest.php (hunk 1 above)
Comment (ax-ml) [reply test/Unit/WrapperRunner/WrapperRunnerTest.php]: Done, assert is now more exact

**Review by Slamdunk — CHANGES_REQUESTED** [review]
I tried to revert `src/WrapperRunner/SuiteLoader.php` to the `7.x` branch, and the test in this PR still succeed, this means that the changes are not tested.

Could you please prove the bug with a failing test? Otherwise the risk to re-introduce it in the future is very high.

**Review by Slamdunk — APPROVED** [review]
